### ISSUE TITLE
[3.3.5a] Spell id 57330 that has been learned show in TrainerList as GREEN all the way and can't be learned !

### ISSUE THREAD

**Issue by teetylive** [TrinityCore/TrinityCore#13950]
CORE: 2492eddcf2ae+ 2015-01-22 11:48:06 +0000 (3.3.5 branch)
DB:TDB 335.57 Update to 2015_01_22_00_world.sql
After DK learn 57623(Horn of Winter - Rank 2) , 57330(Horn of Winter - Rank1) show in TrainerList as GREEN all the way and can't be learned !

**Comment by Aokromes** [comment]
In fact it can be learned, but it's still show on trainer.

**Comment by Rushor** [comment]
This hasn't been fixed some time ago by https://github.com/TrinityCore/TrinityCore/commit/fccdba38420a8818a4ffd8fde51dbc2a1dfb18a5 ?

**Comment by teetylive** [comment]
IS this a client bug? when WorldSession::SendTrainerList(ObjectGuid guid, const std::string& strTitle)  called,57330(Horn of Winter - Rank1)  in TrainerList is GRAY,but after learning any other spell,WorldSession::HandleTrainerBuySpellOpcode(WorldPacket& recvData) called, 57330(Horn of Winter - Rank1)  in TrainerList is GREEN（supposed to be GRAY）. If you click GREEN 57330spell, HandleTrainerBuySpellOpcode return, because[code]    // can't be learn, cheat? Or double learn with lags...
    if (_player->GetTrainerSpellState(trainer_spell) != TRAINER_SPELL_GREEN)
        return;
[code]
All in all,if you want to go on learning other spells, you must click one by one spell to skip the 57330 spell.

**Comment by danlapps** [comment]
Is this still a valid issue or has it been fixed in https://github.com/TrinityCore/TrinityCore/commit/fccdba38420a8818a4ffd8fde51dbc2a1dfb18a5 as @Rushor  suggested ?

**Comment by Killyana** [comment]
This still happen on rev. 0ebc15e6f48b but it's just cosmetic.

**Comment by danlapps** [comment]
Ok, trying to clean old issues that has been fixed over the time but are still open

**Comment by teetylive** [comment]
This still happen ! ! has not been fixed!

**Comment by Rushor** [comment]
stop confirming shit if you don't have anything mentionable to add to the ticket.

better issue with better description and spelllinking https://github.com/TrinityCore/TrinityCore/issues/16482
