### ISSUE TITLE
LFG

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14039]
https://github.com/TrinityCore/TrinityCore/commit/cb3fcea26e9d4566987b0ea69e1498e414c703a9 
TDB: 11.57
OS: Windows 7

Greetings. I'm having problem. I have 27 players in Queue for LFG, but group are not beign created.

In queue it showing there are 1 still missing. Still Heal or Tank.

I try to log tank, but it say damage missing. I try to log heal, but it say tank missing.

I have enabled in logs. I'm getting all time spam 2015-01-21_17:44:12 Player: GUID Full: 0x00000000000c79e2 Type: Player Low: 817634 not ingame while retrieving his LockedDungeons.
2015-01-21_18:09:29 Player: GUID Full: 0x000000000008acea Type: Player Low: 568554 not ingame while retrieving his LockedDungeons.
2015-01-21_18:09:30 Player: GUID Full: 0x000000000008acea Type: Player Low: 568554 not ingame while retrieving his LockedDungeons.
2015-01-21_18:09:47 Player: GUID Full: 0x000000000008acea Type: Player Low: 568554 not ingame while retrieving his LockedDungeons.
2015-01-21_18:09:53 Player: GUID Full: 0x000000000008acea Type: Player Low: 568554 not ingame while retrieving his LockedDungeons.
2015-01-21_18:09:57 Player: GUID Full: 0x000000000008acea Type: Player Low: 568554 not ingame while retrieving his LockedDungeons.
2015-01-21_18:10:06 Player: GUID Full: 0x000000000008acea Type: Player Low: 568554 not ingame while retrieving his LockedDungeons.
2015-01-21_18:21:35 Player: GUID Full: 0x00000000000c8be7 Type: Player Low: 822247 not ingame while retrieving his LockedDungeons.
2015-01-21_18:25:20 Player: GUID Full: 0x00000000000c443e Type: Player Low: 803902 not ingame while retrieving his LockedDungeons.

After restart groups are created normally without problem. But after 1-2 hours, it won't to create group. Maybe offline players is not removed correctly ?

**Comment by Shandu** [comment]
may we know which rev. u are using?

**Comment by Frytiks** [comment]
Ye sorry. I'm using https://github.com/TrinityCore/TrinityCore/commit/cb3fcea26e9d4566987b0ea69e1498e414c703a9 
TDB: 11.57
OS: Windows 7

**Comment by Frytiks** [comment]
New information. Sometimes group created for some players, but i don't know why sometimes not creating. Also i test it on older rev https://github.com/TrinityCore/TrinityCore/commit/1c0fc0a1eea8dc5ae1581b67b94473e669375902 with uptime 2 days and multiple times reload config, and groups get created all time, but on my actual rev. sometimes not created. I'm sure @jackpoz should can solve it.

**Comment by jackpoz** [comment]
as for those "not ingame while retrieving his LockedDungeons" logs, you should check if those players are ingame or not

**Comment by Frytiks** [comment]
@jackpoz Here is log -> http://fbe.am/vGy

**Comment by jackpoz** [comment]
is that a full log in debug mode from worldserver startup ?

**Comment by Frytiks** [comment]
@jackpoz This is logging LFG.log, i enabled logs in config.

**Comment by jackpoz** [comment]
that's not a log in Debug mode, you need to set it in worldserver.conf https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L3162

**Comment by Aokromes** [comment]
#10191

**Comment by jackpoz** [comment]
@Frytiks the "not ingame" log warnings should be fixed now

**Comment by Frytiks** [comment]
@jackpoz thanks, but this not solve last player missing for create group, or ?

**Comment by jackpoz** [comment]
No idea, I can't reproduce that bug and I need some logs with Logger.lfg INFO enabled to figure out why that happens.
It's still better to try it with my last changes, maybe it fixed some issues too.

**Comment by Frytiks** [comment]
@jackpoz "not ingame" log warning is now fixed. Also i see groups now more created than before. But still getting this in logs.

2015-02-16_18:47:33 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000a2f65 Type: Player Low: 667493]
2015-02-16_18:53:07 [Player: Perzeus (GUID Full: 0x0000000000043860 Type: Player Low: 276576, Account: 251016)] on group GUID Full: 0x1f50000000000359 Type: Group Low: 857 but LFG has group GUID Full: 0x0000000000000000 Type: None Low: 0 saved... Fixing.
2015-02-16_19:06:45 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000cd127 Type: Player Low: 839975]
2015-02-16_19:18:12 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_19:19:06 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_19:19:28 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_19:19:45 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_19:19:55 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_19:20:12 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_19:22:10 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000c152a Type: Player Low: 791850]
2015-02-16_19:22:24 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000c152a Type: Player Low: 791850]
2015-02-16_19:29:35 [Player: Manasaber (GUID Full: 0x0000000000087947 Type: Player Low: 555335, Account: 316352)] on group GUID Full: 0x1f50000000000434 Type: Group Low: 1076 but LFG has group GUID Full: 0x0000000000000000 Type: None Low: 0 saved... Fixing.
2015-02-16_19:35:34 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf74 Type: Player Low: 839540]
2015-02-16_19:44:59 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000cd127 Type: Player Low: 839975]
2015-02-16_19:49:11 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000cca39 Type: Player Low: 838201]
2015-02-16_19:55:45 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_20:19:19 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_20:22:33 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000cd127 Type: Player Low: 839975]
2015-02-16_20:23:05 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf74 Type: Player Low: 839540]
2015-02-16_20:30:53 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_20:33:12 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000a2f65 Type: Player Low: 667493]
2015-02-16_20:45:34 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_20:48:01 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000cc535 Type: Player Low: 836917]
2015-02-16_20:48:19 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000cc535 Type: Player Low: 836917]
2015-02-16_20:48:23 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000cc535 Type: Player Low: 836917]
2015-02-16_21:01:17 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:01:27 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:01:43 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:01:44 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:01:44 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:02:11 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:02:26 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000a2f65 Type: Player Low: 667493]
2015-02-16_21:02:32 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:03:34 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]
2015-02-16_21:08:05 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000c152a Type: Player Low: 791850]
2015-02-16_21:16:22 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf74 Type: Player Low: 839540]
2015-02-16_21:27:04 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000c152a Type: Player Low: 791850]
2015-02-16_21:27:34 [Player: Arantisia (GUID Full: 0x0000000000071454 Type: Player Low: 463956, Account: 293423)] on group GUID Full: 0x1f50000000000504 Type: Group Low: 1284 but LFG has group GUID Full: 0x0000000000000000 Type: None Low: 0 saved... Fixing.
2015-02-16_21:34:07 [Player: Luxwarlock (GUID Full: 0x00000000000c6be1 Type: Player Low: 814049, Account: 304906)] on group GUID Full: 0x1f50000000000309 Type: Group Low: 777 but LFG has group GUID Full: 0x0000000000000000 Type: None Low: 0 saved... Fixing.
2015-02-16_21:37:34 [Player: Totalblond (GUID Full: 0x0000000000001fec Type: Player Low: 8172, Account: 192678)] on group GUID Full: 0x1f50000000000445 Type: Group Low: 1093 but LFG has group GUID Full: 0x0000000000000000 Type: None Low: 0 saved... Fixing.
2015-02-16_21:48:03 Guids: ERROR! Player multiple times in queue! [GUID Full: 0x00000000000ccf0b Type: Player Low: 839435]

**Comment by Frytiks** [comment]
@jackpoz Got crashlog today, after your commit. http://pastebin.com/HjV8VYzT 

OS: Linux
rev: https://github.com/TrinityCore/TrinityCore/commit/890d1fe57dfe6d92f9bbd47ba627374485ea4813
DB: TDB 11.57

**Comment by jackpoz** [comment]
Assertion fixed in https://github.com/TrinityCore/TrinityCore/commit/dcb500388c0cb4b0ee1b2f86efa43909383fe406

**Comment by Frytiks** [comment]
@jackpoz Can you re-open ? The problem is not fixed, in debug logs, i don't have anything. For example: 4 players are queued. There showing Healer Missing. I logged Healer, but i not get joined to party where is healer missing. It will create new group for me, where i'm only one.

**Comment by Aokromes** [comment]
#10191
