### ISSUE TITLE
[3.3.5] Mirror Image problem to start attack

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#14877]
Problem 1:
When using the spell the images only begin to attack the enemy if the enemy moves or if its owner move.

Way to reproduce: Place 2 characters in Duel, use the mirror image and let the two standing characters. Note that the images will not attack.
If you move the enemy they will begin to attack.
If you move the owner (mage), the mage has to move to a distance that the mirror to move too, only then they will start to attack.

Problem 2:
Another problem is that when the target is in "CC" images should stop attacking. The mechanical work when the "CC" is applied after the images have been calls, however when the "CC" is used before you call them they start attacking ignoring the mechanics.

How to reproduce: Use Polymorph (spell id = 12826) at a target, after that use the mirror image and move (so she start the attack, because of the problem above). Check that it will strike the target even in poly. However if you cast polymorph after it were called they will no longer attack.

Problem 3:
The spell rotation of the images is also wrong. They should start attacking with fireblast, use 2 frost bolt, fireblast, 2 frost bolt ...
Video showing the operation: https://youtu.be/rxRrcq1cf98?t=15s or https://youtu.be/chpymKHkb5I?t=46s

Currently the TC, they are starting to attack with frost bolt, and after 2 frost bolt the fireblast not always being used, most often after the second frost bolt them stand still for about 1.5 ~ 3 sec and return to attack .

spell id 55342 = [Mirror Image]
Trinity Core rev. 3aa177410010e75934703be9247245881be73490

**Comment by Keader** [comment]
For the second problem, solved by adding the old script of Mirror Image that was in npcs_pet.cpp in older versions of TC.

```diff
diff --git a/src/server/scripts/Pet/pet_mage.cpp b/src/server/scripts/Pet/pet_mage.cpp
index 0d6353c..dac2550 100644
--- a/src/server/scripts/Pet/pet_mage.cpp
+++ b/src/server/scripts/Pet/pet_mage.cpp
@@ -54,6 +54,59 @@ class npc_pet_mage_mirror_image : public CreatureScript
                 owner->CastSpell(me, SPELL_MAGE_CLONE_ME, false);
             }
 
+			void EnterCombat(Unit* who)
+			{
+				if (spells.empty())
+					return;
+
+				for (SpellVct::iterator itr = spells.begin(); itr != spells.end(); ++itr)
+				{
+					if (AISpellInfo[*itr].condition == AICOND_AGGRO)
+						me->CastSpell(who, *itr, false);
+					else
+						if (AISpellInfo[*itr].condition == AICOND_COMBAT)
+						{
+							uint32 cooldown = GetAISpellInfo(*itr)->realCooldown;
+							events.ScheduleEvent(*itr, cooldown);
+						}
+				}
+			}
+
+			void UpdateAI(uint32 diff)
+			{
+				if (!UpdateVictim())
+					return;
+
+				events.Update(diff);
+				bool hasCC = false;
+				if (me->GetCharmerOrOwnerGUID() && me->GetVictim())
+					hasCC = me->GetVictim()->HasAuraType(SPELL_AURA_MOD_CONFUSE);
+
+				if (hasCC)
+				{
+					if (me->HasUnitState(UNIT_STATE_CASTING))
+						me->CastStop();
+					me->AI()->EnterEvadeMode();
+					return;
+				}
+
+				if (me->HasUnitState(UNIT_STATE_CASTING))
+					return;
+
+				if (uint32 spellId = events.ExecuteEvent())
+				{
+					if (hasCC)
+					{
+						events.ScheduleEvent(spellId, 500);
+						return;
+					}
+
+					DoCast(spellId);
+					uint32 casttime = me->GetCurrentSpellCastTime(spellId);
+					events.ScheduleEvent(spellId, (casttime ? casttime : 500) + GetAISpellInfo(spellId)->realCooldown);
+				}
+			}
+
             // Do not reload Creature templates on evade mode enter - prevent visual lost
             void EnterEvadeMode() override
             {

**Comment by Goatform** [comment]
diff --git a/src/server/scripts/Pet/pet_mage.cpp b/src/server/scripts/Pet/pet_mage.cpp
index 0d6353c..bcd9e49 100644
--- a/src/server/scripts/Pet/pet_mage.cpp
+++ b/src/server/scripts/Pet/pet_mage.cpp
@@ -52,6 +52,13 @@ class npc_pet_mage_mirror_image : public CreatureScript
                 // here should be auras (not present in client dbc): 35657, 35658, 35659, 35660 selfcast by mirror images (stats related?)
                 // Clone Me!
                 owner->CastSpell(me, SPELL_MAGE_CLONE_ME, false);
+
+                if (!me->GetVictim())
+                    if (owner && owner->GetVictim())
+                        AttackStart(owner->GetVictim());
+
+                    if (me->GetVictim() && me->GetVictim() != owner->GetVictim())
+                        AttackStart(owner->GetVictim());
             }

             // Do not reload Creature templates on evade mode enter - prevent visual lost

**Comment by Goatform** [comment]
Check fix from @13705

**Comment by Keader** [comment]
I had already tested.

Tested: https://github.com/TrinityCore/TrinityCore/issues/13705#issuecomment-74426650 and https://github.com/TrinityCore/TrinityCore/issues/13705#issuecomment-67877001

**Comment by jackpoz** [comment]
please open PRs when there's code involved so we can comment it (for example there's no need to check if spells are empty, the for loop is enough. UpdateAI() also has dead code that is never executed if hasCC is true.

**Comment by Keader** [comment]
Updated the code with their suggestions Jack
ty :+1:

**Comment by tkrokli** [comment]
@Keader : contact me for a walkthrough on maintaining your fork and creating a PR. Skype: trondbk

**Comment by jackpoz** [comment]
@tkrokli stop creating PRs about code you are not going to maintain, it's not useful at all. The code author is supposed to create the PR or someone with enough C++ knowledge to be able to edit it according to feedback

**Comment by tkrokli** [comment]
@jackpoz : I understand your concern, but this time I intended to show Keader how to do it himself, either via chat or via TeamViewer, on his computer. Then again, I should probably stop meddling at all.

**Comment by jackpoz** [comment]
ah teaching others is way much more helpful to everyone, so he can update it on his own too

**Comment by Keader** [comment]
Another problem I have just noted is: After 2 frost bolts images are about 1.5 ~ 3 sec without attacking, not sure if this is correct

**Comment by Keader** [comment]
With the fix #14896, the problem 2 is solved. No need https://github.com/TrinityCore/TrinityCore/issues/14877#issuecomment-111596120 code
Probably it happened by mistake in time to start the attack.

**Comment by Goatform** [comment]
Yeah, but that fix from PTR is still not good to merge it... Well, that's my opinion.

**Comment by robinsch** [comment]
What about just using PetAI instead of CasterAI?

**Comment by tkrokli** [comment]
I share the sentiment that the fix in #14896 is incomplete, since the mirror images should do the same attacks as the owner, not attack random targets. But since I don't play caster much, I don't actually know.

**Comment by Ofinka** [comment]
updated https://github.com/Ofinka/TrinityCore/commit/8b334f6baac773ec8511fb1fdb1108146981a426

**Comment by robinsch** [comment]
@Ofinka I bet there is a better way to handel this, WAY too much code.

**Comment by Keader** [comment]
@Ofinka Work for me.
You could look after the "rotation" of spell of Images? They are stopping the attack, which does not occur in the blizzard.

**Comment by Goatform** [comment]
I agree with @robinsch

**Comment by Ofinka** [comment]
@robinsch Ur right, there is much code but i didnt want to mess core stuff with this issue. I daresay  this pet_mage script works well.

**Comment by Keader** [comment]
Problem 3 fixed by: cca6462f5e8df7d12c9340a70777ae696ab212c1

**Comment by ShinDarth** [comment]
Are there any news about this? @Ofinka code is valid for latest rev?

**Comment by Keader** [comment]
Closed by: 263f127d075d56be8fd19ef36871bf245bc4bdcc
