### ISSUE TITLE
[3.3.5] Upper black rock spire Stadium fight

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#15101]
During the stadium fight, enemies doesn't attack players in the beginning but the wait to be attacked

PS: also Blackwing lair seems bugged, the first boss are acting weird when controlled... we will try again.

DB: 335.58
Trinity Core rev 0b1355b

**Comment by ikir83** [comment]
Also only a single wave of enemy spawn (at least when we tried)

**Comment by Killyana** [comment]
Waves attacking players can be easily fixed by SAI, the problem is the missing waves:
https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp#L68

**Comment by LEO33SoFo** [comment]
I confirm this issue still happens as of 9d959123e68020a83c780f53a967b3589cb70786.

**Comment by Surggurrian** [comment]
The newest Release still have at least 2 issues on Stadium fight:
1.The minion waves do not work correctly;
2.After players kill Rend and Gyth, the exit door does not open, and Lord Victor Nefarius just pace back and forth on the up floor.
