### ISSUE TITLE
[Events/Midsummer Fire Festival] Lord Ahune

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1516]
[http://www.wowhead.com/npc=25740 Lord Ahune], the boss of the Midsummer Fire Festival, is not scripted (atm it does nothing) and has no loot.

Also, the npc [http://www.wowhead.com/npc=25710 Numa Cloudsister] in The Slave Pens is not spawned (it's related to the chain-quest that leads to the summoning of the boss), and also the gameobject needed to summon the boss (I suppose it's [http://www.wowhead.com/object=187882 this one]) is missing.

**Comment by sirikfoll** [comment]
Still unfinished. Probably there's a lot of things wrong, since I barely know C++, I'll appreciate if  somebody take a look and give some suggestions ^^
https://gist.github.com/sirikfoll/d79c4cb268cb34f85683  boss_ahune.cpp
https://gist.github.com/sirikfoll/2f260a95d76922e60ab0 instance_the_slave_pens.cpp
https://gist.github.com/sirikfoll/d265c0a258e7cb294cd7 the_slave_pens.h

**Comment by Nyeriah** [comment]
It's that the first thing you try to script? It looks quite consistent (with few things here and there to be checked but overall quite nicely structured). Usually it's way easier for us to direct people to the right way if they open pull requests though :)

**Comment by tkrokli** [comment]
@sirikfoll : I have added your (Trista's) code in my local source copy, in case you would like some assistance in creating a PR for this. I added `Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp`
to the file list in `/src/server/scripts/Outland/CMakeLists.txt` in my local source copy, `branch:Ahune`.

**Comment by sirikfoll** [comment]
I intend to open a PR soon, but there's still major issues, that i really think that should be fixed before that, but I don't have enough info for that. 
For instance:
1. The spell that do the "knockback" when you get too close to Ahune (http://www.wowhead.com/spell=46734) it has a Pull effect, so it probably need to be cast by a 'bunny'. But what 'bunny'? Where should it be placed?
2. Everything regarding the Slippery Floor;
3. Spells that should periodically trigger another spells  don't work;
http://www.wowhead.com/spell=46810
 and http://www.wowhead.com/spell=46371
4. unknown "Beam" spells:
4.1. Frozen core casts before ahune's resurface, maybe http://www.wowhead.com/spell=46396? 
4.2. the beam that the totem cast on Ahune, http://www.wowhead.com/spell=46363 is correct?
4.3. beam that flamecallers cast, on itself and in the totem.
4.4. the blue beam used on Ahune's summoning.

If you know something, please share

**Comment by Keader** [comment]
@Aokromes issue already fixed

**Comment by Demonid** [comment]
The second part of this report is still valid, http://www.wowhead.com/npc=25710 Numa Cloudsister] is still missing in 50146b22296aac18f4ee07ed09a8bdc5cf19725c

**Comment by RedSonja** [comment]
She is still missing for me too.
