### ISSUE TITLE
[Crash] ObjectWorldLoader::Visit

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15775]
Since last commit I have crashes every 10-15 minutes. I have lot of crashlogs. Several of them:

http://pastebin.com/JNFzv2nT
http://pastebin.com/w48kTG2T
http://pastebin.com/6V8EvjjD
http://pastebin.com/fUhs0afT
http://pastebin.com/7hQMrEgG

20b4e6f03adc29e486e20866222a42e8935704b4

**Comment by Shauren** [comment]
Only ONE of these crashes is in ObjectWorldLoader::Visit - a proposed fix for it already exists here https://github.com/TrinityCore/TrinityCore/issues/15684#issuecomment-151183774 please test it.
2 of them (Map::RemoveOldCorpses -> GetGuidValue) are still unknown to me why they happen
and finally 2 logs with WorldObject::~WorldObject will be fixed soon.

* you reported 3 different crashes in one issue.

**Comment by Pirricli** [comment]
Ok sorry, I saw that was differente but all of them appeared since the 20b4e6f03adc29e486e20866222a42e8935704b4 commit.

**Comment by Pirricli** [comment]
http://pastebin.com/6dmFX7fV
http://pastebin.com/JAjDa3Ni

Should I open another issue for the other crash? I have more logs.

**Comment by Shauren** [comment]
Do not report any more ObjectWorldLoader::Visit crashes unless you get them AFTER you apply the fix from https://github.com/TrinityCore/TrinityCore/issues/15684#issuecomment-151183774

**Comment by Laintime** [comment]
Confirm http://pastebin.com/Sb6cpZTF

**Comment by digz6666** [comment]
Confirmed b72e723acef97781c82c50094532ae8296391329

**Comment by Re3os** [comment]
confirm http://pastebin.com/bgkhm3wN

**Comment by Shauren** [comment]
WorldObject::~WorldObject crash fixed in 1d17475791cae66beafda1e2c3198a66d355086f

**Comment by Re3os** [comment]
@Shauren http://pastebin.com/bgkhm3wN

**Comment by digz6666** [comment]
@Shauren applied the fix but it's still crashing. I see that there's 1 method definition added, but where is that method is called?

**Comment by Aokromes** [comment]
workaround: disable bones creation.
