### ISSUE TITLE
[3.3.5] Archmade Leryda doesn't give any quest

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#16389]
http://www.wowhead.com/npc=18253/archmage-leryda

She didn't give quest at all even if i see a big question mark on his head. She should give quest when player become friendly with Violet eye.

I will confirm that other player have the same issue later.

DB: 335.60
TrinityCore: 09a65163673c

**Comment by ikir83** [comment]
Yes other player have the same issue

**Comment by Rushor** [comment]
i think there was a commit a few days ago, which fixed this problem

**Comment by ikir83** [comment]
AH ok, i've update TrinityCore 2 weeks ago, i wanted to do again yesterday but we had this Karazhan raid :-P So i've waited. I will update tonight probably so i can confirm the fix is in. Thanks

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16214

yeah fits to the 2 weeks of missing updates - pls close the issue if everything works fine after you updated your db :)

**Comment by Killyana** [comment]
Yes this issue was fixed.

**Comment by ikir83** [comment]
Tried now, after update and with version i still can't talk to her e6a7818a9a
big question mark, no dialog appear

![quest_leryda](https://cloud.githubusercontent.com/assets/10136428/12624226/3672e686-c52e-11e5-8846-acf8070c98ab.jpg)

**Comment by ikir83** [comment]
My DB is 335.60 with auto update one but it seems it DB related or not?

**Comment by Saben65** [comment]
Type this query in your DB and tell me what `text_ids` show up.

```SQL
SELECT * FROM `gossip_menu` WHERE `entry` = 8441;
```

**Comment by ikir83** [comment]
I've manually executed this query i've found in the other thread
`DELETE FROM `npc_text` WHERE `ID` = 10884;`
and now it works anyway doesn't the DB updates itself?

Anyway this is what i see with your query
![schermata 2016-01-28 alle 20 24 11](https://cloud.githubusercontent.com/assets/10136428/12656204/349af798-c5fd-11e5-8b9a-8510a412a189.png)

**Comment by tkrokli** [comment]
Your DB is not up to date, at least not for this NPC and her `gossip_menu` table. It should look like this:
```
 entry  text_id  
------  ---------
  8441    10546
```
Run this query:
```sql
DELETE FROM `gossip_menu` WHERE `entry`= 8441 AND `text_id`= 10884;
```
Then restart worldserver and test again.

Notice that the commit https://github.com/TrinityCore/TrinityCore/commit/34847ea44a48911c113cd3ee6faf5d42be81ad4f 13 days ago (2016-01-16) removed both the empty line and `gossip_menu`.`text_id` 10884 :
```sql
--
DELETE FROM `npc_text` WHERE `ID` = 10884;
DELETE FROM `gossip_menu` WHERE `entry`=8441 AND `text_id`=10884;
```
So you may as well run this query directly, just to be sure that there is no empty `npc_text` line either.

**Comment by ikir83** [comment]
OK perfect thanks, The problem is why my DB is not uptodate since autoupdate is turned on. Anyway i will ask on TrinityCore forum.

**Comment by tkrokli** [comment]
Unless you have got any custom content in your `world` DB, the best way to test it is to empty your world DB completely, then save a copy of `TDB_full_335.60_2015_11_07.sql` in your core folder (same place as authserver +  worldserver) and make sure that you do this on the same computer as you cloned your source, so the files /sql/updates/world/*.sql are available for worldserver to reload them into `world` DB.

**Comment by ikir83** [comment]
I've edited some column in the DB (like process of mounts and NPC respawn time), but this shouldn't stop autoupdates, or not?

**Comment by tkrokli** [comment]
No, but if your DB was updated before you edited, any custom settings won't be changed.
You need to reset the `world`.`updates` table to get all the world SQL files reinserted / read again.

**Comment by ikir83** [comment]
Tried but i've noticed DB335.61 is not out yet, so probably this is the reason i didn't get the fix
