### ISSUE TITLE
[3.3.5] ICC/Professor Putricide: Volatile Ooze/Gas Cloud does not attack the raid

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18925]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://wowwiki.wikia.com/wiki/Professor_Putricide

>  The Volatile Ooze targets and roots a random player and moves towards its target...

> The Gas Cloud follows a random player and applies Gaseous Bloat, a dot which requires a lot of healing...

Unstable Experiment does not attack the raid in Phase 1. If the raid does not attack the unstable experiment, Volous Ooze and Gas Cloud accumulate in the room. When phase 2 begins the unstable experiment works fine.

**Current behaviour:**
Volatile Ooze/Gas Cloud does not attack the raid in phase 1. 

**Expected behaviour:**
Volatile Ooze/Gas Cloud should attack the raid in phase 1.

**Steps to reproduce the problem:**
1. Go to Professor Putricide's room and attack him.
2. Wait until Putricide performs an "Unstable Experiment".

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  591a255

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DeActiver** [comment]
soloTest one person in this case is not true

**Comment by Noryad** [comment]
If raid attacks Volatile Ooze or Gas Cloud the "Unstable Experiment" enter in combat, but by default the "Unstable Experiment" is passive and should not. That is the reason of this issue.

**Comment by Noryad** [comment]
Confirmed in c6060dd.

![los dos](https://cloud.githubusercontent.com/assets/30839/22661828/b43b7d8a-ec5b-11e6-8c41-d9c94771b6b5.jpg)

**Comment by Noryad** [comment]
Fixed in recent commits, issue invalid on bbc6799.

**Comment by Keader** [comment]
Still not working in 1af895dc97ccb6a2f7c62eb63062a6f5c94c8a9c
