### ISSUE TITLE
Core/GameObject: cannot loot gameobject

### ISSUE THREAD

**Issue by uroborusLogos** [TrinityCore/TrinityCore#19523]
Description:
[master]GameObject can't looting or opening.(for quests)

Current behaviour:
GameObject can't looting or opening.
Tested on several areas.
Cannot click on game objects (No interaction icon).

Branch(es) : 7.2
TC rev. hash/commit:  d56671a

**Comment by Aokromes** [comment]
Update your core before reporting such bugs. Maybe it was fixed on a newer revision.

**Comment by uroborusLogos** [comment]
already updated (Core and db).
Compiled today.

**Comment by DJBoxer** [comment]
Yeah bug still exists any quest where you have to find items such as objects or free/break chains release captives from cages. you can`t click item. same as quest in tauren area where you have to click the crate to hand in quest no longer works as you can`t click crate.

**Comment by Ulduar2** [comment]
Maybe need update GO flags?
Like https://github.com/TrinityCore/TrinityCore/commit/14dce619763708b2ab6abaa4f321caa808c31bcd
But for GO.
