### ISSUE TITLE
Destructible GameObjects as a floor

### ISSUE THREAD

**Issue by Golrag** [TrinityCore/TrinityCore#19865]
**Description:**

Some destructible gameobjects that are used as a floor return the wrong floorZ when using .gps command. This leads to creatures falling through them. This is not always the case on the gameobject as on some places it returns the right value.

**Current behaviour:**
See above.

**Expected behaviour:**

.gps command should return the right z coordinate

**Steps to reproduce the problem:**

1.  .go xyz 483.304047 -2168.442627 840.856812 631
2. .gps
3. Notice the floorZ value.
4. Aggro Lich King and let him chase you

**Branch(es):**

- 3.3.5
- master ?

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/107d6260668f825a2a72e7694b43e7940b3c88aa

**Operating system:** Win10

**Comment by Treeston** [comment]
Also happens on 1660bb7d27d6f42b49012a6b57e3c2b2eab20fd3 - not caused by f6c849729b27b77228704b595de3adaf24da2c10.

Console reports
```
Could not load MMAP name:Icecrown Citadel, id:631, x:31, y:36 (mmap rep.: x:31, y:36)
VMap file './vmaps/631.vmtree' does not exist
```

**Comment by tkrokli** [comment]
@Treeston : I found `631.vmtree` in my latest extraction of vmaps, maybe you haven't extracted new vmaps after commit https://github.com/TrinityCore/TrinityCore/commit/c35793941b3aae9b54dce92389aa528d40050754 (**Core/VMaps: Fix LoS in Strand of the Ancients** (#19847))?

**Comment by Treeston** [comment]
> That file does exist.

**Comment by tkrokli** [comment]
Yes, I misread. Sorry.

**Comment by Treeston** [comment]
```
<Shauren> its caused by this
<Shauren> https://github.com/TrinityCore/TrinityCore/commit/c35793941b3aae9b54dce92389aa528d40050754
<Shauren> i think i need to remind you that both ToC floor and LK area are gameobjects
<Shauren> that means no pathfinding
<Shauren> except apparently there is that unrendered WMO spawn there (just like the sota gates) which provided pathfinding (and also blocked it in sota)
```
Tagging and assigning to @Golrag

**Comment by Golrag** [comment]
I juste made the PR, I am afraid I don't know much about extracting vmaps & wmo's etc and maybe @Warpten would be a better choice for fixing this :/

**Comment by Treeston** [comment]
All listed issues fixed by commit cfb0f9f tagged above (thanks for the quick investigation, @Shauren).

**Comment by SeTM** [comment]
The problem is not fixed to the end, in some places of the platform of the Lich King, the height is taken incorrectly. For example, next to the portal of teleportation.

**Comment by Shauren** [comment]
Portal? What? There is no portal on the platform

**Comment by SeTM** [comment]
There is a portal where players appear on the platform. But on the last rev there everything is fine. There are problems in other places, for example -http://i.prntscr.com/l4X-FnDfSlScezI_9wec2A.jpeg

**Comment by Killyana** [comment]
Confirm @SeTM comment on rev. b2823f388ac3

**Comment by Killyana** [comment]
Here a position where FloorZ != Z 
X: 452.136780 Y: -2087.799805 Z: 840.856934 Orientation: 5.298477
grid[32,28]cell[6,0] InstanceID: 536
ZoneX: 69.298904 ZoneY: 67.391762
0.000000 FloorZ: 825.880737 Have height data (Map: 1 VMap: 0 MMap: 1)

**Comment by Warpten** [comment]
probably an error in the vertices extracted, ill check it out later

**Comment by Killyana** [comment]
Yes the issue was introduced by https://github.com/TrinityCore/TrinityCore/commit/c35793941b3aae9b54dce92389aa528d40050754#diff-97edc20817c42622adaefabfd511126fR351
I wasn't happen with the old vmaps.

**Comment by Warpten** [comment]
<sigh> reversing 3.3.5

**Comment by Warpten** [comment]
for later:

collidable faces: `flags & 8 || (flags & 36) == 32`
trans faces: `flags & 1 && flags & 0x24`
render faces: `flags & 36 == 32`
detail faces: `flags & 4`
group collision faces :`flags & 8`

nocamcollide: `flags & 2`
group color : `flags & 8`

**Comment by Killyana** [comment]
So we must revert the commit?

**Comment by Treeston** [comment]
Let @Warpten deal with it.

**Comment by Keader** [comment]
1 more: #https://github.com/TrinityCore/TrinityCore/issues/19976

**Comment by ccrs** [comment]
This makes LK encounter almost unbearable... can we give some priority?

**Comment by Golrag** [comment]
@Warpten I removed this part of the code
```
bool isRenderFace = (MOPY[2 * i] & WMO_MATERIAL_RENDER) && !(MOPY[2 * i] & WMO_MATERIAL_DETAIL);
bool isDetail = (MOPY[2 * i] & WMO_MATERIAL_DETAIL) != 0;
bool isCollision = (MOPY[2 * i] & WMO_MATERIAL_COLLISION) != 0;

if (!isRenderFace && !isDetail && !isCollision)
    continue;
```
and restored the previous check (with updated enum names) and it 'seems' to fix the issue. Sadly I know nothing about this code and I am not sure about any of this :p
```
if (MOPY[2 * i] & WMO_MATERIAL_DETAIL || !(MOPY[2 * i] & (WMO_MATERIAL_COLLISION | WMO_MATERIAL_RENDER)))
    continue;
```
- LK Platform fixed (with given coordinates)
- Sota LoS is working as intended now, and couldn't reproduce the LK issue with given coordinates.

- Tested ToC with the worms, one of them is always going a little bit under the floor but when using .gps on the exact same coordinates above the floor, it show the right ones so my guess here is some kind of scripting problem.
For those wondering:
those were the coordinates of the NPC when he was emerging back from the ground
```.go xyz 574.321594 165.828339 383.395660``` use some higher z value if you don't want to spawn in/under the floor :p

Only thing I'm not sure about is this: When standing on the solid part of the pillars on LK platform it will still show FloorZ on the platform instead of the solid part of the pillar. While before I made the changes that I described above, it would show the correct ones so I'm not really sure which of the two are the indended behaviours.
http://i.imgur.com/xvGqDnk.jpg

**Comment by Warpten** [comment]
If you have a cataclysm client, use https://github.com/Warpten/MeshViewer.
a. Enter world
b. Inject into client (button in app)
c. go to platform (it doesn't like you changing maps on the fly)
d. load geometry

you will get the geometry that the server sees.

If you use 335 i can MAYBE cook up a fixed version but as of right now its gonna need to be cata

**Comment by Golrag** [comment]
I don't have a cata client :p
Found this also https://wowdev.wiki/WMO/v17#MOPY_chunk which made me want to create a PR already as I was more certain about the fix

**Comment by Warpten** [comment]
gimme a sec

**Comment by Warpten** [comment]
you can also open tile 6313631 in jackpoz's recastdemo https://github.com/jackpoz/recastnavigation

**Comment by Golrag** [comment]
```mmaps_generator 631 --debugOutput true``` tried this command, but couldn't find 6313631
6313530 was the last value I could select in the list

**Comment by Warpten** [comment]
you can select a specific tile too.. for some reason the mmaps gen is very iffy

**Comment by PatricNox** [comment]
This is still present on stock TC.
2 ways to reproduce:

* TOC10 -> Worms emerge up from ground, see how they're stuck beneath
* ICC10  -> Raging spirits phase 2, see how theyre spawned and stuck beneath

**Comment by Aokromes** [comment]
9614f9d
