### ISSUE TITLE
[master] trainer NPC requires random spell on player

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#20057]
**Description:**

Hello, i tried to update all trainers legion for PR this after. But i have two problems
Maybe SendTrainerList need an update?

**Current behaviour:**

1. Each restart i have the spell requirement "Herb Gathering" and sometimes an other spell "Arena Preparation" or "Venomous Bite" (it's totally random after a restart, sometimes he disappear when you click again on trainer)
2. The progress bar appear per moment when you don't have the profession

[**look screenshoot**](http://imgur.com/a/w5e7I)

**Expected behaviour:**

1. Only level and "Herbalism (skill value)" need appear
2. The progress bar need appear only when you have the profession

**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/fc6b488620282620eada92a6615643cdc9c5411f

**TDB version:**  TDB 720.00

**Operating system:** Debian

**Comment by Shauren** [comment]
Test 1) after 120d2ebe4f878fdb59055dc15136a5331eedc523
2) definitely not fixed by that commit

**Comment by DoctorKraft** [comment]
1) With this commit it's good now for random spell :) But i have always a second spell requirement "Herb Gathering" / "Alchemy" for spell with step. Example : [Expert Alchemist](http://www.wowhead.com/spell=3465/expert-alchemist) **It's only visual**

[screenshot alchemy](http://imgur.com/a/Yy19o)
[screenshot herbalism](http://imgur.com/a/ixMkd)

2. Yeah it's not fixed, but now the progress bar is here all times. Maybe this lua can help ? [here](https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/AddOns/Blizzard_TrainerUI/Blizzard_TrainerUI.lua#L138)

Thanks !

**Comment by DoctorKraft** [comment]
EDIT : I have find something interesting when i remove this code [(in lua)](https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/AddOns/Blizzard_TrainerUI/Blizzard_TrainerUI.lua#L145)
```lua
if ( rankModifier > 0 ) then
    statusBar.rankText:SetFormattedText(TRADESKILL_RANK_WITH_MODIFIER, rank, rankModifier, maxRank);
else
    statusBar.rankText:SetFormattedText(TRADESKILL_RANK, rank, maxRank);
end
```
and replace by

```lua
    statusBar.rankText:SetFormattedText(TRADESKILL_RANK, rank, maxRank);
```
the bar appear perfectly, maybe the initialization of `TRADESKILL_RANK_WITH_MODIFIER` are wrong ?

**Comment by Aokromes** [comment]
2nd #9353 if the 1st is fixed, close this ticket and continue posting on #9353

**Comment by DoctorKraft** [comment]
1st not totally fixed ^^

**Comment by DoctorKraft** [comment]
Update : i find the problem now for resolve 1st and 2nd but not idea to resolve this. I can't sniff on retails :/

In packet [`TrainerListSpell` ](https://github.com/TrinityCore/TrinityCore/blob/b453e124231a90321fe79fbf3a62acdcfa54a691/src/server/game/Handlers/NPCHandler.cpp#L162) when you set `spell.ReqAbility[maxReq]` at 0, this resolve all problems (1 & 2).

**Comment by DoctorKraft** [comment]
This issue and #9353 can be closed it's fixed in https://github.com/TrinityCore/TrinityCore/commit/0cd5179726f91cc163910dd0806d622fe86d9a8c https://github.com/TrinityCore/TrinityCore/commit/b85d46138bf6cd0fd50a0f8060f1512002ced731 https://github.com/TrinityCore/TrinityCore/commit/fac8ccf7e0981d3ea376aeff30788d2e53fca92f

**Comment by Shauren** [comment]
Not really, that skill value isnt fixed - to fix it we need to add the profession skillline to updatefields with max = 0
