### ISSUE TITLE
Release spirit aggro issue

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21481]
**Description:**

For some reason, if you release your spirit close to a mob that can aggro onto you, the mob will aggro for a split second and reset. This can be seen easily on boss encounters where you would normally die close to the boss home position. Not necessarily any "negative" issues related to this that I have noticed so far, but definitely not working as intended.

**Current behaviour:**

When you release spirit, mobs will aggro onto your ghost prior to being teleported to the graveyard.

**Expected behaviour:**

Mobs should not aggro onto your ghost when releasing.

**Steps to reproduce the problem:**

1. Die close to a mob that can aggro onto you, easily seen on raid bosses
2. Release spirit while observing creature behaviour from a second account

**Branch(es):** 3.3.5

**TC rev. hash/commit:** eb7d22d

**TDB version:**  TDB 335.64

**Operating system:** Windows Server 2012

**Comment by Foereaper** [comment]
Literally as I submitted this I was notified by a player that they had a boss maul their corpse while dead earlier today, ie. boss kept attacking after he died. I have not been able to recreate, but figured I should post it in case it is relevant.

**Comment by Aokromes** [comment]
Try updating to at least 7cff1b540c96d9e2cf82b244cc0d1618bf5b090f

**Comment by Foereaper** [comment]
Will do as soon as I can, but probably won't be till Saturday, in case someone is able to confirm/deny this by then :)

**Comment by Killyana** [comment]
Cannot reproduce on rev. 94b5d9bfa119

**Comment by Foereaper** [comment]
Just tested it on 94b5d9b and it still happens, try it near a boss that has an enter/exit combat yell message, and they'll yell when you release your spirit, tested on a couple different bosses in Naxxramas

**Comment by Killyana** [comment]
I tested with Lord Marrowgar.

**Comment by Foereaper** [comment]
https://youtu.be/69xrPaL6uuI

See the yell after the spirit release

**Comment by Killyana** [comment]
Yes confirm with Instructor Razuvious.

**Comment by Foereaper** [comment]
I had it happen with Heigan as well

**Comment by Killyana** [comment]
Cannot reproduce on rev. 4b8410717f5f

**Comment by Faq** [comment]
@natnat201193 still happens? on what rev?

**Comment by natnat201193** [comment]
oh i haven't tested it for a long while so im not sure if it does still happen. im just assuming it does seen as this issue has not been closed. ill Retest it and comment again as soon as i have time.

**Comment by Aokromes** [comment]
This maybe have been fixed by 7bc16e2ee6ace39588a991537ff28811000a16c2

**Comment by Treeston** [comment]
Very likely this still happens in situations as described by @natnat201193 in previous comment. We revive then teleport later, movement notifies likely happen before reviving.

willfix
