### ISSUE TITLE
Crash on _CreateAuraApplication

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21856]
**Current behaviour:**

https://gist.github.com/Gooyeth/fbbae9815c04abd98daa2eb9cc2d7907

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 71a4f68d66f95c018ceb1c5fe80755fc4ab43be9

**Operating system:** Debian 9

**Comment by jackpoz** [comment]
by the crashlog it seems like it happens in Utgarde Pinnacle in the Skadi fight, were you able to reproduce the crash again ?

**Comment by jackpoz** [comment]
spell_skadi_reset_check_SpellScript seems to reset the fight a bit too often too

**Comment by Winchester1987** [comment]
@jackpoz 
I do not want to detract the post, but how do you realize which NPC is by reading the crashlog?
I have the same problem (reported #22306) and I would like to figure out how this happens.

**Comment by jackpoz** [comment]
spellId=47574 appears in the crashlog and that's used in Utgare Pinnacle by Skadi https://wotlk.evowow.com/?spell=47574#used-by-npc .
The function InstanceMap::Update() in the stacktrace also shows it's an instance and not a continent.

**Comment by jackpoz** [comment]
hopefully fixed by https://github.com/TrinityCore/TrinityCore/commit/518e6299ca08a362bc3709daaaa5e5d5633d1bf1

**Comment by Aokromes** [comment]
still crashing on 71dde16ce9a9

https://gist.github.com/Aokromes/5282f9ff4bea0b4f0cfd697784bc6a48

**Comment by jackpoz** [comment]
I will just remove the assert since it's VERY OBVIOUS it can be triggered by simply casting spells (asserts are not supposed to be triggered unless the impossible happens)

**Comment by Shauren** [comment]
No, don't do that, this means that there is a logic error somewhere else in spell/aura code and, as you said, the impossible is happening
