### ISSUE TITLE
Quest 11571 - Learning to Communicate

### ISSUE THREAD

**Issue by Rhyme** [TrinityCore/TrinityCore#2250]
"Luckily, a friend taught me a water breathing spell, which I will cast upon you."

The aforementioned water breathing spell lasts three seconds. Shouldn't it last ten or something?

Rev: bb921ae+
DB: TDB 335.11.41

**Comment by Aokromes** [comment]
This is fixed already no?

**Comment by Rushor** [comment]
nope the buff which is given by taking the quest is still missing:
https://www.youtube.com/watch?v=yz3uvS6TG2I&feature=player_detailpage#t=0

anyone knows the id?

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f4ee5ad58f6e95442191a08e37df389107d6b0ea
