### ISSUE TITLE
[3.3.5a] Professor Putricide is broken after update core to latest

### ISSUE THREAD

**Issue by zqaazq** [TrinityCore/TrinityCore#23727]
![WoWScrnShot_081919_180731](https://user-images.githubusercontent.com/52695159/63276947-12ad7880-c2ad-11e9-979c-fd83c7c79f4d.jpg)
**Description:**

Players can`t attack Professor Putricide

**Current behaviour:**

he stands on the balcony in the phase of helping the rotface or festergut
no matter who kill first

**Expected behaviour:**

players can attack Professor Putricide

**Steps to reproduce the problem:**

1. Go to ICC

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d56dd89635ce26feb6a6b507ed8a54d3cfe0efc7

**Operating system:**

Debian 9

**Comment by Killyana** [comment]
Update your core: https://github.com/TrinityCore/TrinityCore/commit/7fa990edc6cbae05e8b68da58313fd675ac5fa81
And don't kill Rotface or Festergut until the gate is closed

**Comment by Killyana** [comment]
This happen only on 10 man normal horde version only, in this specific case the boss have this flags:
* UNIT_FLAG_IMMUNE_TO_PC (0x100)
* UNIT_FLAG_NOT_SELECTABLE (0x2000000)

**Comment by Killyana** [comment]
This require script change
``` sql
-- Update Putricide difficulties entry with the correct unit flag and speed
UPDATE `creature_template` SET `unit_flags`=33554688, `speed_walk`=1.2, `speed_run`=1.71429 WHERE `entry` IN (36678,38431,38585,38586);

**Comment by jackpoz** [comment]
what kind of script change ? adding or deleting stuff ?

**Comment by Killyana** [comment]
I don't really know, the boss remains stuck in combat with `unit_flags`=33554688, maybe Treeston can take a look to this issue.

**Comment by shenhuyong** [comment]
Add into boss_professor_putricide() can fix this problem.

            void JustEnteredCombat(Unit* who) override
            {
                EngagementStart(who);
            }

**Comment by Treeston** [comment]
Units do not start engaging when they enter combat. That's intentional.

Units start engaging _when something threatens them_.

**Comment by shenhuyong** [comment]
So it breaks his BossAI::EnterEvadeMode(why) to reach home in phase PHASE_ROTFACE and PHASE_FESTERGUT.

bool CreatureAI::_EnterEvadeMode(EvadeReason /*why*/)
{
    if (!IsEngaged())
        return false;

**Comment by Treeston** [comment]
If it uses `DoZoneInCombat`, that calls `EngageWithTarget`, which calls `SetThreat`. There should be threat.

If there isn't, that's the actual issue. Use .debug threat on him to find out why the threat isn't there.

**Comment by Shauren** [comment]
There should be no threat in the case where Putricide just overlooks Festergut and Rotface encounters

**Comment by Treeston** [comment]
If it calls DoZoneInCombat, it should have 0.0f threat references (it, assumedly, also has PASSIVE set during this phase, so it won't chase).

**Comment by Killyana** [comment]
The flag UNIT_FLAG_IMMUNE_TO_PC must avoid npc being engaged with player, but it fails in this case:

.debug combat
Combat refs: (Combat state: 1 | Manager state: 1)
[PvE] Test (SpawnID 0)

.debug threat
Professor Putricide (GUID 3) does not threaten any units.
Professor Putricide (GUID 3, SpawnID 201294) is not engaged, but still has a threat list? Well, here it is:
   1.   Test   (GUID 11)  - threat 0.000000 [OFFLINE]
End of threat list.

**Comment by MrSmite** [comment]
>Test (GUID 11) - threat 0.000000 [OFFLINE]

Wow, Professor Putricide is such a badass he aggros when you sit down at your computer, before you even log in!

Anyway, seems like there's something wrong with clearing threat when a GUID goes offline.

**Comment by jackpoz** [comment]
That's offline threat reference, not offline player. 2 different things.

**Comment by Rokmusic** [comment]
Sory, How fixing?

**Comment by illfated** [comment]
There is no known solution yet.
Combined coding + scripting experience may be needed.

**Comment by ckegg** [comment]
I am not sure if the following issue I am seeing is related to this problem. If you get wiped at Rotface, the ooze flood is not stopping and will get doubled and so on if you wipe again (ex: 2-> 4 -> 6 -> 8 and more). I found that [EVENT_ROTFACE_OOZE_FLOOD](https://github.com/TrinityCore/TrinityCore/blob/92d83c3c2eaba3f5b58dc98472318872f3a54706/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp#L399) in Professor Putricide is not stopping even Rotface made a [EnterEvadeMode()](https://github.com/TrinityCore/TrinityCore/blob/92d83c3c2eaba3f5b58dc98472318872f3a54706/src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp#L173) call to Professor Putricide. Meaning that if you aggro Rotface once more after wiping, two events are running, or more.
While [EVENT_ROTFACE_OOZE_FLOOD](https://github.com/TrinityCore/TrinityCore/blob/92d83c3c2eaba3f5b58dc98472318872f3a54706/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp#L604) is not stopping, does it keep setting phase to [PHASE_ROTFACE](https://github.com/TrinityCore/TrinityCore/blob/92d83c3c2eaba3f5b58dc98472318872f3a54706/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp#L606) ?

**Comment by Treeston** [comment]
retest after 23fd193

**Comment by Killyana** [comment]
Putricide no longer cast spells in Festergut and Rotface encounters.

**Comment by Aokromes** [comment]
this was fixed already no?

**Comment by Killyana** [comment]
No

**Comment by jackpoz** [comment]
> **Description:**
> Players can`t attack Professor Putricide

I was able to attack it after killing Rotface and Festergut (waiting for the door to close each time and for Putricide to go to the balcony).

@Killyana do you mean some other issue is not fixed ? It would be better to open a new one then.

**Comment by Killyana** [comment]
It's the same issue, .go c id 36627 aggro and kill the boss when the gate close, and you will remains in combat with Putricide.
If you kill Festergut after that Putricide will loose the non selectable flag + immune to PC and then you will no longer be in combat.

So the issue is with the unit flag immune to PC and In combat with players
