### ISSUE TITLE
Broken links in CONTRIBUTING.md and the TrinityCore GitHub Wiki

### ISSUE THREAD

**Issue by TranceAccount** [TrinityCore/TrinityCore#25094]
**Description:**

As I was looking for the coding guidelines, I encountered the problem that the TrinityCore GitHub Wiki and the CONTRIBUTING.md files both contain links to documents on the TrinityCore website/(old) forum, which I do not have access to or no longer exist.

**Expected behaviour:**

The following links used in the CONTRIBUTING.md file and in the GitHub wiki should redirect to the corresponding documents.

CONTRIBUTING.md:
1. https://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/
2. https://www.trinitycore.org/f/topic/1518-trouble-with-your-trinity-install-readme-1st-faqs/
3. https://www.trinitycore.org/f/topic/345-howto-properly-install-git-on-windows-fix-trinitycore-rev-1970-01-01-000000-0000/
4. https://www.trinitycore.org/f/topic/58-wdb-fields/

https://github.com/TrinityCore/TrinityCore/wiki:
1. http://collab.kpsn.org/display/tc/Requirements
2. http://www.trinitycore.org/f/topic/10656-updating-or-starting-with-trinitycore-issues/
3. http://www.trinitycore.org/f/topic/6-trinitycore-developing-standards/
4. https://www.trinitycore.org/f/topic/1518-trouble-with-your-trinity-install-readme-1st-faqs/
5. https://www.trinitycore.org/f/topic/58-wdb-fields/

**Steps to reproduce the problem:**

1. Click on the links given in the above section.
2. Watch it load and give error 404.

**Operating system:** Windows 10 with Firefox Browser version 78.0.2

**Comment by illfated** [comment]
Looks like the PR #25096 should resolve the issues you have posted.

**Comment by TranceAccount** [comment]
It fixes the problems with CONTRIBUTING.md indeed, thanks.
However, the links are still broken in the GitHub wiki page, not sure if anyone uses that actually.

**Comment by Carbenium** [comment]
@TranceAccount Thanks for the heads-up! They should be fixed now.
