### ISSUE TITLE
{Quest} As the Crow Flies

### ISSUE THREAD

**Issue by boujii** [TrinityCore/TrinityCore#5723]
http://old.wowhead.com/quest=9718
http://www.youtube.com/watch?v=G1qQwGXIWx8
http://www.xfire.com/video/a27d4/

Missing shape Transformation.

What steps will reproduce the problem?
1. Upon receiving the quest, a player gets Quest Item: Stormcrow Amulet http://old.wowhead.com/item=25465
2. Use the quest item, near NPC: Ysiel Windsinger http://old.wowhead.com/npc=17841
3. Using the quest item is supposed to turn the player into NPC: Stormcrow Shape http://old.wowhead.com/spell=31606,
 which should make the player look like a black crow. 
Problem: Using quest item won't turn the player into NPC: Stormcrow Shape, which makes the player look like a black crow
http://imageshack.us/photo/my-images/192/wowscrnshot031312164545.jpg/

.go creature 63514
.cast 31606

You go for the ride just fine. Just no transformation effect

**Comment by Killyana** [comment]
Fixed

**Comment by Rushor** [comment]
the text issue was not fixed yet, it should say some stuff:

Ysiel Windsinger whispers: It's just like the structure you described at Umbrafen Lake. Does this mean the naga are pumping water out of all the lakes in Zangarmarsh?
Ysiel Windsinger whispers: The naga are even pumping the water out of their own lake! What purpose could that possibly serve?
Ysiel Windsinger whispers: There! Those pipes all appear to be connected to that structure. It can't possibly fit all the water they've been stealing. Where are they keeping it?
Ysiel Windsinger whispers: What we say explains what happened in the Dead Mire. There was a lake here once. If we don't stop the naga, all of the marsh will soon look like this?

**Comment by Rushor** [comment]
dbc data for this:

<details>
```sql
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13232, 512, 0, 530, -139.463, 5534.72, 44.1766, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13233, 512, 1, 530, -123.028, 5578.13, 55.292, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13234, 512, 2, 530, -159.45, 5764.78, 54.2086, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13235, 512, 3, 530, -173.455, 5943.54, 38.8936, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13236, 512, 4, 530, -204.134, 6161.65, 33.3198, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13237, 512, 5, 530, -188.014, 6295.55, 41.3198, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13238, 512, 6, 530, -29.5121, 6310.45, 53.7421, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13239, 512, 7, 530, 105.258, 6328.36, 71.4308, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13240, 512, 8, 530, 275.707, 6370.6, 78.0977, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13241, 512, 9, 530, 578.919, 6343.93, 45.3208, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13242, 512, 10, 530, 669.292, 6487.03, 66.4117, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13243, 512, 11, 530, 708.701, 6656.54, 57.6645, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13244, 512, 12, 530, 710.05, 6899.36, 23.8341, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13245, 512, 13, 530, 626.79, 7109.99, 33.4861, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13246, 512, 14, 530, 479.394, 7009.36, 46.5778, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13247, 512, 15, 530, 353.75, 6725.58, 68.1706, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13248, 512, 16, 530, 487.158, 6382.78, 38.3701, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13249, 512, 17, 530, 468.966, 6168.36, 74.8085, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13250, 512, 18, 530, 463.786, 5833.58, 71.7173, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13251, 512, 19, 530, 469.809, 5756.17, 66.7644, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13252, 512, 20, 530, 482.009, 5630.49, 44.1998, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13253, 512, 21, 530, 417.176, 5587.9, 58.3476, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13254, 512, 22, 530, 216.629, 5525.81, 74.8198, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13255, 512, 23, 530, 10.0463, 5523.18, 39.9223, 0, 0, 0, 0);
INSERT INTO `dbc_taxipathnode` (`m_ID`, `m_PathID`, `m_NodeIndex`, `m_ContinentID`, `m_LocX`, `m_LocY`, `m_LocZ`, `m_flags`, `m_delay`, `m_arrivalEventID`, `m_departureEventID`) VALUES (13256, 512, 24, 530, -144.302, 5532.78, 34.5142, 0, 0, 11225, 11225);
```

</details>

**Comment by Killyana** [comment]
As for [QUEST] Spiritual Insight 12028 we don't have any way to do this via the DB.

**Comment by Rushor** [comment]
for 'As the Crow Flies' we also don't even have m_arrivalEventID or m_departureEventID, meh :(

**Comment by offl** [comment]
I saw some serverside spells for this quest.
```sql
SELECT * FROM `spell_dbc` WHERE `ID` = 31728 OR `ID` BETWEEN 31773 AND 31777;
```

**Comment by Rushor** [comment]
```sql
DELETE FROM `creature_text` WHERE `entry`=CreatureID;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES 
(17841, 0, 0, 'It''s just like the structure you described at Umbrafen Lake.  Does this mean the naga are pumping water out of all the lakes in Zangarmarsh?', 15, 0, 100, 0, 0, 0, 14706, 'Ysiel Windsinger'),
(17841, 1, 0, 'The naga are even pumping the water out of their own lake!  What purpose could that possibly serve?', 15, 0, 100, 0, 0, 0, 14712, 'Ysiel Windsinger'),
(17841, 2, 0, 'There!  Those pipes all appear to be connected to that structure.  It can''t possibly fit all the water they''ve been stealing.  Where are they keeping it?', 15, 0, 100, 0, 0, 0, 14713, 'Ysiel Windsinger'),
(17841, 3, 0, 'What we saw explains what happened in the Dead Mire.  There was a lake here once.  If we don''t stop the naga, all of the marsh will soon look like this!', 15, 0, 100, 0, 0, 0, 14714, 'Ysiel Windsinger');
```

**Comment by illfated** [comment]
True, we still need that text inserted.
